# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Craft < Formula
  desc ""
  homepage "https://github.com/Spacewalkio/homebrew-tools"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spacewalkio/Craft/releases/download/v1.0.0/craft_1.0.0_Darwin_x86_64.tar.gz"
      sha256 "144d262a0df10a4de89d1eac9c49c3b9f01ee143dc0b9a390c184cafc893df0a"

      def install
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spacewalkio/Craft/releases/download/v1.0.0/craft_1.0.0_Darwin_arm64.tar.gz"
      sha256 "8fcebaaccf1909359af769a2777f82c975411f60ff3202afade164b0afa7b9af"

      def install
        bin.install "craft"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Spacewalkio/Craft/releases/download/v1.0.0/craft_1.0.0_Linux_x86_64.tar.gz"
      sha256 "54b382549a1b7f7c1b0d4c87a0288c0673c449e70c17ab48d08956231f81d937"

      def install
        bin.install "craft"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spacewalkio/Craft/releases/download/v1.0.0/craft_1.0.0_Linux_arm64.tar.gz"
      sha256 "79650d3050ff902947e5bc5eaf4c9843b963549c03d4d22d409911c2f5811272"

      def install
        bin.install "craft"
      end
    end
  end
end
